name       : libkexiv2
version    : 20.04.2
release    : 39
source     :
    - https://cdn.download.kde.org/stable/release-service/20.04.2/src/libkexiv2-20.04.2.tar.xz : 81ea2e2c818bb9d7d52025aecf1a2a348e68f822b78285cd887dd46e44a640f2
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : programming
optimize   : lto
summary    : Exiv2 library interface for KDE
description: |
    Libkexiv2 is a wrapper around Exiv2 library to manipulate pictures metadata as EXIF/IPTC and XMP.
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(exiv2)
    - pkgconfig(libssh)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
