name       : libkexiv2
version    : 17.08.3
release    : 7
source     :
    - https://cdn.download.kde.org/stable/applications/17.08.3/src/libkexiv2-17.08.3.tar.xz : 220b0c86132b84a32a674bf404174a51419a3ea40f4f7096541a0c39cc342049
license    :
    - BSD-3-Clause
    - GPL-2.0
    - LGPL-2.0
component  : programming
summary    : Exiv2 library interface for KDE
description: |
    Libkexiv2 is a wrapper around Exiv2 library to manipulate pictures metadata as EXIF/IPTC and XMP.
builddeps  :
    - pkgconfig(exiv2)
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
