name       : libkexiv2
version    : 17.12.0
release    : 8
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.0/src/libkexiv2-17.12.0.tar.xz : 2db7cc98631d9e400ab105a9973caafbdb13360f6ce317b46cdd46c490ec5847
license    :
    - BSD-3-Clause
    - GPL-2.0
    - LGPL-2.0
component  : programming
optimize   : lto
summary    : Exiv2 library interface for KDE
description: |
    Libkexiv2 is a wrapper around Exiv2 library to manipulate pictures metadata as EXIF/IPTC and XMP.
builddeps  :
    - pkgconfig(exiv2)
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
