name       : libkexiv2
version    : 20.12.2
release    : 48
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.2/src/libkexiv2-20.12.2.tar.xz : eb364ea254d8d72317124e725b4a5b2db0d45c627020ad934f6e1f7f66174882
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : programming
summary    : Exiv2 library interface for KDE
description: |
    Libkexiv2 is a wrapper around Exiv2 library to manipulate pictures metadata as EXIF/IPTC and XMP.
optimize   : lto
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(exiv2)
    - pkgconfig(libssh)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
