name       : libkexiv2
version    : 22.04.2
release    : 63
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.2/src/libkexiv2-22.04.2.tar.xz : e395c8cc4291dd03e97b739b9b8a224a3c5be335d19caded97c5af902cdd317b
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : programming
summary    : Exiv2 library interface for KDE
description: |
    Libkexiv2 is a wrapper around Exiv2 library to manipulate pictures metadata as EXIF/IPTC and XMP.
optimize   : lto
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(exiv2)
    - pkgconfig(libssh)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
