name       : libkexiv2
version    : 20.04.1
release    : 38
source     :
    - https://cdn.download.kde.org/stable/release-service/20.04.1/src/libkexiv2-20.04.1.tar.xz : 91c23aacc2fc51970a5bd141de689c51c454d72b489ff842b5b8534c21c7b9a4
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : programming
optimize   : lto
summary    : Exiv2 library interface for KDE
description: |
    Libkexiv2 is a wrapper around Exiv2 library to manipulate pictures metadata as EXIF/IPTC and XMP.
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(exiv2)
    - pkgconfig(libssh)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
