name       : libkexiv2
version    : 18.04.0
release    : 12
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.0/src/libkexiv2-18.04.0.tar.xz : fec30c8a4d9e0cfd3a00f980c7add91f885f997cc7ff3fe4b8dbef268d5acd87
license    :
    - BSD-3-Clause
    - GPL-2.0
    - LGPL-2.0
component  : programming
optimize   : lto
summary    : Exiv2 library interface for KDE
description: |
    Libkexiv2 is a wrapper around Exiv2 library to manipulate pictures metadata as EXIF/IPTC and XMP.
builddeps  :
    - pkgconfig(exiv2)
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
