name       : libkexiv2
version    : 17.08.1
release    : 4
source     :
    - https://download.kde.org/stable/applications/17.08.1/src/libkexiv2-17.08.1.tar.xz : 4c5e763852fe2140aedda4f33979d13b0bd4a9eb8fdb23ebf7bb246a696a1c1b
license    :
    - BSD-3-Clause
    - GPL-2.0
    - LGPL-2.0
component  : programming
summary    : Exiv2 library interface for KDE
description: |
    Libkexiv2 is a wrapper around Exiv2 library to manipulate pictures metadata as EXIF/IPTC and XMP.
builddeps  :
    - pkgconfig(exiv2)
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
