name       : libkexiv2
version    : 19.08.0
release    : 28
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.0/src/libkexiv2-19.08.0.tar.xz : 42bb1a8b69efbb4ab8b1d939279d3eb02b2d8030bcb917739f4f61fb5a10db15
license    : GPL-2.0-or-later
component  : programming
optimize   : lto
summary    : Exiv2 library interface for KDE
description: |
    Libkexiv2 is a wrapper around Exiv2 library to manipulate pictures metadata as EXIF/IPTC and XMP.
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(exiv2)
    - pkgconfig(libssh)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
