name       : libkexiv2
version    : 16.12.0
release    : 1
source     :
    - http://download.kde.org/stable/applications/16.12.0/src/libkexiv2-16.12.0.tar.xz : 6c0b8d3db56e92cbfd6dcd1c03190778254b4383d323024def87d4d2c4b73405
license    :
    - BSD-3-Clause
    - GPL-2.0
    - LGPL-2.0
component  : programming
summary    : Exiv2 library interface for KDE
description: |
    Libkexiv2 is a wrapper around Exiv2 library to manipulate pictures metadata as EXIF/IPTC and XMP.
builddeps  :
    - pkgconfig(exiv2)
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
