name       : libkexiv2
version    : 17.08.2
release    : 6
source     :
    - https://download.kde.org/stable/applications/17.08.2/src/libkexiv2-17.08.2.tar.xz : d1f86afd77d722818c7656d793e7026180ecc95fcc8b522d4ff334333ce2a108
license    :
    - BSD-3-Clause
    - GPL-2.0
    - LGPL-2.0
component  : programming
summary    : Exiv2 library interface for KDE
description: |
    Libkexiv2 is a wrapper around Exiv2 library to manipulate pictures metadata as EXIF/IPTC and XMP.
builddeps  :
    - pkgconfig(exiv2)
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
