name       : libkexiv2
version    : 18.04.2
release    : 14
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.2/src/libkexiv2-18.04.2.tar.xz : f37eec77a432ed7b03c87e78dc4af5f6de7d0868d2a31de194b6e38a174317b3
license    :
    - BSD-3-Clause
    - GPL-2.0
    - LGPL-2.0
component  : programming
optimize   : lto
summary    : Exiv2 library interface for KDE
description: |
    Libkexiv2 is a wrapper around Exiv2 library to manipulate pictures metadata as EXIF/IPTC and XMP.
builddeps  :
    - pkgconfig(exiv2)
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
