name       : libkexiv2
version    : 18.08.2
release    : 18
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.2/src/libkexiv2-18.08.2.tar.xz : 79eb7031c73e95d83f4076f130009864562aecefe8823f7b82af635f50f9fe7f
license    :
    - BSD-3-Clause
    - GPL-2.0
    - LGPL-2.0
component  : programming
optimize   : lto
summary    : Exiv2 library interface for KDE
description: |
    Libkexiv2 is a wrapper around Exiv2 library to manipulate pictures metadata as EXIF/IPTC and XMP.
builddeps  :
    - pkgconfig(exiv2)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
