name       : libkexiv2
version    : 18.12.1
release    : 21
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.1/src/libkexiv2-18.12.1.tar.xz : 43eae5763854dbbcabbbe500a1a7221a50aae9d159560095fe0c0cf71a09f3c9
license    : GPL-2.0-or-later
component  : programming
optimize   : lto
summary    : Exiv2 library interface for KDE
description: |
    Libkexiv2 is a wrapper around Exiv2 library to manipulate pictures metadata as EXIF/IPTC and XMP.
builddeps  :
    - pkgconfig(exiv2)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
