name       : libkexiv2
version    : 19.12.2
release    : 35
source     :
    - https://cdn.download.kde.org/stable/release-service/19.12.2/src/libkexiv2-19.12.2.tar.xz : 60a7efd97b47d08865043a13bc245b827bf152c85b8e0f2afed647469d95f430
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : programming
optimize   : lto
summary    : Exiv2 library interface for KDE
description: |
    Libkexiv2 is a wrapper around Exiv2 library to manipulate pictures metadata as EXIF/IPTC and XMP.
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(exiv2)
    - pkgconfig(libssh)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
